name: "rss-merge"
author: "hxhacking"
description: "Merge RSS feeds"
inputs:
  PATH:
    description: "File path"
    required: true
    default: "feeds.yml"
  CLIENT_TIMEOUT_SECONDS:
    description: ""
    default: "30"
  AUTHOR_NAME:
    description: ""
    default: "github-actions"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
