name: "feeds-merge"
author: "hxhacking"
description: "Merge RSS feeds"
inputs:
  FEEDS_PATH:
    description: "feeds.yml path"
    required: true
    default: "feeds.yml"
  CLIENT_TIMEOUT:
    description: ""
    default: "30"
  AUTHOR_NAME:
    description: ""
    default: ${{ github.repository }}
  FEED_LIMIT:
    description: "entries limit per feed"
    default: "300"
  FEED_LINK:
    description: "feed link"
    default: "https://github.com/${{ github.repository }}"
  FEEDS_FOLDER:
    description: "feeds folder"
    default: "feeds"
outputs:
  FEEDS_FOLDER:
    description: "GENERATED FEEDS FOLDER"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "rss"
  color: "orange"