name: Integration Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: 91go/feeds-merge@main
        env:
          feeds-yaml: testdata/feeds.yml
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.FEEDS_FOLDER }}" == "feeds"
